services:
  postgres:
    image: postgres:18
    container_name: backend-postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: backend
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d backend"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
